version: '3.8'

services:
  api: # Evolution API
    image: atendai/evolution-api:homolog
    container_name: evolution_api
    env_file:
      - ./.env
    # Adiciona a seção environment para garantir que EVOLUTION_API_KEY seja definida
    environment:
      # Mapeia a AUTHENTICATION_API_KEY do .env para EVOLUTION_API_KEY que a API espera
      EVOLUTION_API_KEY: ${AUTHENTICATION_API_KEY}
      # Você pode adicionar outras variáveis específicas da API aqui se necessário,
      # mas as outras parecem estar sendo lidas corretamente do .env
      # Exemplo: DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - evolution-net
    # Adicionar healthcheck para garantir que a API esteja escutando
    healthcheck:
      test: ["CMD-SHELL", "apk add curl && curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s # Tempo para a API iniciar antes do primeiro check

  backend: # ConviteCerto
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convitecerto_backend
    env_file:
      - ./.env
    # Garante que o backend também tenha acesso à chave correta (já deve funcionar via .env)
    # environment:
    #   EVOLUTION_API_KEY: ${AUTHENTICATION_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - evolution-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - "6379:6379"
    networks:
      - evolution-net
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: evolution
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - evolution-net
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  evolution-net:
    driver: bridge

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
